-- Generated by nwg-displays on 2026-07-31 at 10:29:33. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.0",
    position = "1920x0",
    scale = 1.33
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@179.96",
    position = "0x0",
    scale = 1.0
})
