-- Generated by nwg-displays on 2026-08-05 at 15:08:54. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "eDP-1"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "eDP-1"
})
